In [46]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [47]:
import tensorflow as tf # type: ignore
import numpy as np

# matrix1 = np.array([np.random.randint(1,5,size=(3,3))])
# matrix2 = np.array([np.random.randint(1,5,size=(3,3))])

# print(matrix1)
# print(matrix2)

matrix1 = np.random.randint(1,5,size=(3,3))
matrix2 = np.random.randint(1,5,size=(3,3))

print(matrix1)
print(matrix2)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)

print(matrix1)
print(matrix2)

[[2 4 1]
 [4 2 1]
 [3 2 4]]
[[3 1 4]
 [2 3 3]
 [3 2 4]]
tf.Tensor(
[[2 4 1]
 [4 2 1]
 [3 2 4]], shape=(3, 3), dtype=int64)
tf.Tensor(
[[3 1 4]
 [2 3 3]
 [3 2 4]], shape=(3, 3), dtype=int64)


In [48]:
matrix_product = tf.matmul(matrix1,matrix2)
matrix_product

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[17, 16, 24],
       [19, 12, 26],
       [25, 17, 34]])>

In [49]:
matrix_sum = tf.add(matrix1,matrix2)
matrix_sum

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[5, 5, 5],
       [6, 5, 4],
       [6, 4, 8]])>

In [51]:
matrix3 = np.random.randint(1, 5, size=(3, 3)).astype(np.float32)
print(matrix3)
matrix_determinant = tf.linalg.det(matrix3)
print(matrix_determinant)

[[2. 1. 3.]
 [2. 4. 1.]
 [3. 2. 3.]]
tf.Tensor(-7.0000005, shape=(), dtype=float32)
